services:
  db:
    image: postgres:15-alpine
    container_name: employee_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: employee_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: employee_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=employee_management;Username=postgres;Password=postgrespassword
      - Jwt__Key=ThisIsASecretKeyThatIsLongEnoughForHMACSHA256Signature
      - Jwt__Issuer=EmployeeApi
      - Jwt__Audience=EmployeeApiClients
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  postgres_data:
